# Generated by Django 5.2.7 on 2025-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=128)),
                ('cpu', models.FloatField(default=0)),
                ('ram', models.FloatField(default=0)),
                ('disk', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
