# Generated by Django 5.2.7 on 2025-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='ping',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
