# Generated by Django 5.2.7 on 2025-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_systemmetric_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetric',
            name='ping',
            field=models.FloatField(default=0),
        ),
    ]
